// Themes the Figma SVG exports in figures/ and writes src/figures/index.ts.
// Strips the ground rect and plate id, maps Figma hex to theme variables, crops the viewBox,
// and adds <title>/<desc> so each figure is a labelled image.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const COLORS = {
  "#0A0D19": "var(--ground)", "#E8E6DF": "var(--ink)", "#8A8F9C": "var(--muted)",
  "#2A3040": "var(--rule)", "#4A5163": "var(--rule-strong)", "#E5A23A": "var(--accent)",
  "#8FB0D6": "var(--blue)",
};
// id: [title, desc, viewBox cropped to content]
const META = {
  g3: ["The idea", "Source meanings on the left, target meanings on the right, both resolved into one graph in the centre.", "0 90 800 430"],
  g4: ["Many to one", "BIRTH_YR, yob and birth_year converge on one target property, year_of_birth.", "0 60 640 290"],
  g5: ["What the agent gets", "A question enters, the relevant part of the model is lit, and a compact context block goes to the agent.", "0 50 1200 320"],
  g6: ["Three studies, one model", "Three public cancer studies converge on OMOP; people, diagnoses and merged patients come out, with dated counts.", "0 55 1200 175"],
  g7: ["The project you have run", "Four months on one line. The mapping sheet grows, then breaks at month nine when a new source arrives.", "0 40 1200 150"],
  g11: ["Wedge to expansion", "Concentric rings: supplied standard models at the core, emergent models around them, any model you define outside.", "20 40 440 400"],
  g7m: ["The project you have run", "Four months on one vertical line. The mapping sheet grows, then breaks at month nine when a new source arrives.", "0 34 358 346"],
  g6m: ["Three studies, one model", "Three public cancer studies converge on OMOP; people, diagnoses and merged patients come out, with dated counts.", "0 36 358 414"],
  g12: ["Ownership chain", "Parcel to property company to holding company to manager, each link labelled with its record. The last link is not in the public record.", "0 115 640 235"],
};

function theme(id, svg) {
  const [title, desc, box] = META[id];
  let out = svg
    .replace(/<svg width="(\d+)" height="(\d+)" viewBox="[^"]+"/, (_, w, h) => `<svg data-w="${w}" data-h="${h}" viewBox="${box}"`)
    .replace(/<rect width="\d+" height="\d+" fill="#0A0D19"\/>\n/, "")
    .replace(/<text[^>]*><tspan[^>]*>G\d+m? &#xb7;[^<]*<\/tspan><\/text>\n/, "")
    .replace(/#([0-9A-F]{6})/g, (m) => COLORS[m] ?? m)
    .replace(/ style="white-space: pre" xml:space="preserve"/g, "")
    .replace(/font-family="IBM Plex Mono"/g, 'font-family="var(--font-mono)"')
    .replace(/font-family="IBM Plex Sans"/g, 'font-family="var(--font-sans)"');
  out = out.replace(
    'xmlns="http://www.w3.org/2000/svg">',
    `xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="${id}-t ${id}-d"><title id="${id}-t">${title}</title><desc id="${id}-d">${desc}</desc>`,
  );
  return { title, desc, svg: out.trim() };
}

const ids = readdirSync(join(here, "..", "figures")).filter((f) => f.endsWith(".svg")).map((f) => f.slice(0, -4)).sort();
const entries = ids.map((id) => {
  if (!META[id]) throw new Error(`no META for ${id}`);
  const { title, desc, svg } = theme(id, readFileSync(join(here, "..", "figures", `${id}.svg`), "utf8"));
  return `  ${id}: { id: ${JSON.stringify(id)}, title: ${JSON.stringify(title)}, desc: ${JSON.stringify(desc)}, svg: ${JSON.stringify(svg)} },`;
});
const ts = `// Generated by scripts/build-figures.mjs from figures/*.svg. Do not edit.
import type { FigureSource } from "../components/figure";

export const figures = {
${entries.join("\n")}
} as const satisfies Record<string, FigureSource>;

export type FigureId = keyof typeof figures;
`;
writeFileSync(join(here, "..", "src", "figures", "index.ts"), ts);
console.log(`wrote src/figures/index.ts (${ids.length} figures, ${(ts.length / 1024).toFixed(1)} KB)`);
