/* Renders one markdown file per A/B arm from src/copy/: COPY.md (control), COPY.a.md, COPY.b.md.
   `--check` exits 1 when any of them is stale.
   Run: node --experimental-strip-types scripts/render-copy.ts [--check] */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";
import type { Copy } from "../src/copy/index.tsx";
import type { Arm } from "../src/copy/variants.ts";
import type { figures as Figures } from "../../../packages/design/src/figures/index.ts";

const HERE = dirname(fileURLToPath(import.meta.url));

/* The copy modules pull in @sema/design (tsx, package exports), which Node's type stripping cannot
   load on its own; Vite's SSR loader resolves them the same way the app build does. */
async function loadCopy(): Promise<{ arms: readonly Arm[]; figures: typeof Figures }> {
  const vite = await createServer({ root: resolve(HERE, ".."), server: { middlewareMode: true }, appType: "custom", logLevel: "error" });
  try {
    const [variants, design] = await Promise.all([
      vite.ssrLoadModule("/src/copy/variants.ts") as Promise<{ arms: readonly Arm[] }>,
      vite.ssrLoadModule("@sema/design") as Promise<{ figures: typeof Figures }>,
    ]);
    return { arms: variants.arms, figures: design.figures };
  } finally {
    await vite.close();
  }
}

const { arms, figures } = await loadCopy();
const outFile = (arm: Arm) => resolve(HERE, arm.id === "control" ? "../COPY.md" : `../COPY.${arm.id}.md`);

const HEADINGS: Record<Exclude<keyof Copy, "figures">, string> = {
  meta: "Page metadata",
  nav: "S0 · Navigation",
  hero: "S1 · Hero",
  idea: "S3a · The idea (rendered before S2)",
  story: "S2 · You've run this project",
  quote: "S3b · Quote wall and two ways in",
  changes: "S4 · What changes for you",
  proof: "S5 · Proof",
  stays: "S6 · What we need, and what stays where",
  why: "S7 · Why now",
  roadmap: "S8 · Roadmap",
  investors: "S10 · Investors (rendered before S9)",
  pilot: "S9 · The pilot",
  footer: "S11 · Footer",
  form: "Form states (both forms)",
  notFound: "404",
};

const SOURCE: Record<Arm["id"], string> = {
  control: "src/copy/base.ts",
  a: "src/copy/variant-a.ts",
  b: "src/copy/variant-b.ts",
};

const preamble = (arm: Arm) => `# Sema landing page copy${arm.id === "control" ? "" : ` · A/B arm ${arm.id}`}

Generated from \`${SOURCE[arm.id]}\` by \`scripts/render-copy.ts\`. Do not edit this file; edit
the source and run \`npm run copy:md\`. \`npm run build\` fails when this file is stale.
${arm.id === "control" ? "" : `\nServed at \`/\` to visitors the middleware assigns to arm \`${arm.id}\`; reachable directly at \`${arm.path.replace(/\.html$/, "")}\`.\n`}
Slot names follow the section keys in \`base.ts\`, so a sign-off row id \`S5__card_blocked_why\`
reads as \`proof · cards · blocked · why\`. Links render as \`text → href\`.

Not sourced from \`${SOURCE[arm.id]}\`: figure titles and descriptions come from
\`packages/design/src/figures/index.ts\`${arm.id === "control" ? "" : ", relabelled by \`src/copy/variant-figures.ts\` where this arm overrides a plate"} (listed below); the labels drawn inside each figure live
in Figma. \`public/404.html\` is still hand-edited; its strings are mirrored under 404.
`;

type Row = { slot: string; copy: string };

/* { text | label, href } pairs render on one row. */
function isLink(v: unknown): v is { text?: string; label?: string; href: string } {
  if (typeof v !== "object" || v === null || !("href" in v) || Object.keys(v).length !== 2) return false;
  return "text" in v || "label" in v;
}

/* Depth-first walk; nested keys join with " · ", array items are 1-based. */
function rows(value: unknown, path: string[] = [], out: Row[] = []): Row[] {
  if (typeof value === "string") out.push({ slot: path.join(" · "), copy: value });
  else if (isLink(value)) out.push({ slot: path.join(" · "), copy: `${value.text ?? value.label} → ${value.href}` });
  else if (Array.isArray(value)) value.forEach((v, i) => rows(v, [...path, String(i + 1)], out));
  else if (typeof value === "object" && value !== null)
    for (const [k, v] of Object.entries(value)) rows(v, [...path, k], out);
  return out;
}

function table(list: Row[]): string {
  const esc = (s: string) => s.replace(/\|/g, "\\|");
  return ["| Slot | Copy |", "|---|---|", ...list.map((r) => `| ${esc(r.slot)} | ${esc(r.copy)} |`)].join("\n");
}

function sections(copy: Copy): string {
  return (Object.keys(HEADINGS) as (keyof typeof HEADINGS)[])
    .map((key) => `## ${HEADINGS[key]}\n\n${table(rows(copy[key]))}`)
    .join("\n\n");
}

/* A variant may relabel plates (copy.figures); applying it here also validates its tokens at build. */
function figureList(copy: Copy): string {
  const merged = { ...figures, ...copy.figures?.(figures) };
  const items = Object.values(merged).map((f) => `- ${f.id}: "${f.title}". ${f.desc}`);
  return `## Figures\n\nTitle and description per figure; in-figure labels are Figma text nodes.\n\n${items.join("\n")}`;
}

function stillOpen(copy: Copy): string {
  const { figures: _plates, ...text } = copy;
  const all = rows(text);
  const counts = new Map<string, number>();
  for (const r of all) for (const m of r.copy.match(/\[[^\]]+\]/g) ?? []) counts.set(m, (counts.get(m) ?? 0) + 1);
  const placeholders = [...counts].map(([k, n]) => `\`${k}\`${n > 1 ? ` ×${n}` : ""}`).join(", ");
  const emptyMail = all.filter((r) => r.copy.endsWith("→ mailto:")).map((r) => `\`${r.slot}\``);
  const lines = [
    `- Placeholders: ${placeholders || "none"}.`,
    `- Empty \`mailto:\` links: ${emptyMail.join(", ") || "none"}.`,
  ];
  return `## Still open\n\n${lines.join("\n")}`;
}

const render = (arm: Arm) =>
  [preamble(arm), sections(arm.copy), figureList(arm.copy), stillOpen(arm.copy)].join("\n\n") + "\n";

function isCurrent(path: string, rendered: string): boolean {
  try {
    return readFileSync(path, "utf8") === rendered;
  } catch {
    return false; /* missing counts as stale */
  }
}

const check = process.argv.includes("--check");
let stale = 0;
for (const arm of arms) {
  const out = outFile(arm);
  const rendered = render(arm);
  if (!check) {
    writeFileSync(out, rendered);
    console.log(`wrote ${out}`);
  } else if (isCurrent(out, rendered)) {
    console.log(`${out} is current.`);
  } else {
    console.error(`${out} is stale. Run: npm run copy:md`);
    stale++;
  }
}
if (stale) process.exit(1);
