/* Renders COPY.md from src/copy/base.ts. `--check` exits 1 when COPY.md is stale.
   Run: node --experimental-strip-types scripts/render-copy.ts [--check] */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { base } from "../src/copy/base.ts";
import { figures } from "../../../packages/design/src/figures/index.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../COPY.md");

const HEADINGS: Record<keyof typeof base, string> = {
  meta: "Page metadata",
  nav: "S0 · Navigation",
  hero: "S1 · Hero",
  story: "S2 · You've run this project",
  idea: "S3 · The idea",
  changes: "S4 · What changes for you",
  proof: "S5 · Proof",
  stays: "S6 · What we need, and what stays where",
  why: "S7 · Why now",
  roadmap: "S8 · Roadmap",
  investors: "S10 · Investors (rendered before S9)",
  pilot: "S9 · The pilot",
  footer: "S11 · Footer",
  form: "Form states (both forms)",
  notFound: "404",
};

const PREAMBLE = `# Sema landing page copy

Generated from \`src/copy/base.ts\` by \`scripts/render-copy.ts\`. Do not edit this file; edit
\`base.ts\` and run \`npm run copy:md\`. \`npm run build\` fails when this file is stale.

Slot names follow the section keys in \`base.ts\`, so a sign-off row id \`S5__card_blocked_why\`
reads as \`proof · cards · blocked · why\`. Links render as \`text → href\`.

Not sourced from \`base.ts\`: figure titles and descriptions come from
\`packages/design/src/figures/index.ts\` (listed below); the labels drawn inside each figure live
in Figma. \`public/404.html\` is still hand-edited; its strings are mirrored under 404.
`;

type Row = { slot: string; copy: string };

/* { text | label, href } pairs render on one row. */
function isLink(v: unknown): v is { text?: string; label?: string; href: string } {
  if (typeof v !== "object" || v === null || !("href" in v) || Object.keys(v).length !== 2) return false;
  return "text" in v || "label" in v;
}

/* Depth-first walk; nested keys join with " · ", array items are 1-based. */
function rows(value: unknown, path: string[] = [], out: Row[] = []): Row[] {
  if (typeof value === "string") out.push({ slot: path.join(" · "), copy: value });
  else if (isLink(value)) out.push({ slot: path.join(" · "), copy: `${value.text ?? value.label} → ${value.href}` });
  else if (Array.isArray(value)) value.forEach((v, i) => rows(v, [...path, String(i + 1)], out));
  else if (typeof value === "object" && value !== null)
    for (const [k, v] of Object.entries(value)) rows(v, [...path, k], out);
  return out;
}

function table(list: Row[]): string {
  const esc = (s: string) => s.replace(/\|/g, "\\|");
  return ["| Slot | Copy |", "|---|---|", ...list.map((r) => `| ${esc(r.slot)} | ${esc(r.copy)} |`)].join("\n");
}

function sections(): string {
  return (Object.keys(HEADINGS) as (keyof typeof base)[])
    .map((key) => `## ${HEADINGS[key]}\n\n${table(rows(base[key]))}`)
    .join("\n\n");
}

function figureList(): string {
  const items = Object.values(figures).map((f) => `- ${f.id}: "${f.title}". ${f.desc}`);
  return `## Figures\n\nTitle and description per figure; in-figure labels are Figma text nodes.\n\n${items.join("\n")}`;
}

function stillOpen(): string {
  const all = rows(base);
  const counts = new Map<string, number>();
  for (const r of all) for (const m of r.copy.match(/\[[^\]]+\]/g) ?? []) counts.set(m, (counts.get(m) ?? 0) + 1);
  const placeholders = [...counts].map(([k, n]) => `\`${k}\`${n > 1 ? ` ×${n}` : ""}`).join(", ");
  const emptyMail = all.filter((r) => r.copy.endsWith("→ mailto:")).map((r) => `\`${r.slot}\``);
  const lines = [
    `- Placeholders: ${placeholders || "none"}.`,
    `- Empty \`mailto:\` links: ${emptyMail.join(", ") || "none"}.`,
  ];
  return `## Still open\n\n${lines.join("\n")}`;
}

const rendered = [PREAMBLE, sections(), figureList(), stillOpen()].join("\n\n") + "\n";

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* missing counts as stale */
  }
  if (current !== rendered) {
    console.error("COPY.md is stale. Run: npm run copy:md");
    process.exit(1);
  }
  console.log("COPY.md is current.");
} else {
  writeFileSync(OUT, rendered);
  console.log(`wrote ${OUT}`);
}
